samotari/crypto-terminal

test/e2e/settings.js

new  test that checks if an error is shown when no MPK in settings

test that checks if an error is shown when no MPK in settings

---

js/payment-methods/bitcoin.js
js/views/settings.js

validation for bitcoin master public key using bitcoin js

validation for bitcoin xpub

---

index.html
js/router.js
js/views/payment-confirmation.js

Does not include the logic to check if the payment has been processed

added route and view for the payment confirmation. 

---

grunt/concat.js
js/abstracts/payment-method.js
js/payment-methods/bitcoin.js
js/util.js

Added payment method abstract class

---

js/abstracts/payment-method.js
js/payment-methods/bitcoin.js
js/views/settings.js

* Now tries all bitcoin networks without requiring a bitcoin network setting. Uses the first network for which the given master public key is valid.
* Fixes inheritance from payment method abstract.

Simplified bitcoin network selection based on xpub

---

grunt/concat.js
js/collections/payment-requests.js
js/init.js
js/models/payment-request.js
package.json

this is other approach for storing the history of payments using [Backbone.Localstorage](https://github.com/jeromegn/Backbone.localStorage)
How to test it:
```javascript
var testPayment = new app.models.PaymentRequest({
currency: 'czk',
address: 'tpubDCY3gJgVweTygKA3Ltw4mQWQgTtKT7BbkP',
confirmed: true,
amount: 23})
app.paymentRequests.add(testPayment)
testPayment.save()
app.paymentRequests.models
app.paymentRequests.models.forEach(function(model){
console.log(model.attributes);
});
```

model and collection payment-requests using library

---

css/views/payment-details.css
css/views/payment-history.css
grunt/concat.js
index.html
js/handlebars.extend/time.js
js/payment-methods/bitcoin.js
js/router.js
js/views/display-payment-address.js
js/views/payment-details.js
js/views/payment-history.js
package.json

new basic payments history view  using momentjs to handle time

view for payments history

---

css/views/payment-confirmation.css
index.html

A confirmation circle with a check inside and a humble animation in css

imporoving Payment success screen issue #30

---

js/views/main.js

added error to show network down on payment

---

js/abstracts/payment-method.js
js/models/payment-request.js
js/views/display-payment-address.js

Added to the payment request history fiat currency that was used for this payment and the exchange rate for the used cryptocurrency that was used for the payment.

adding display currency and exchange rate at the moment of payment / issue #62

---

index.html
js/config.js
js/handlebars.extend/i18n.js
js/i18n.js
js/lang/cs.js
js/lang/en.js
js/models/payment-request.js
js/models/settings.js
js/payment-methods/bitcoin.js
js/payment-methods/litecoin.js
js/views/display-payment-address.js
js/views/main.js
js/views/pay.js
js/views/payment-history.js
js/views/settings.js

Most language strings moved to new [language files](https://github.com/Learn-by-doing/crypto-terminal/tree/09fe4645fb60a0bb927b00286113d83f4ac8a1d0/js/lang).
Language strings in bitcoin and litecoin payment methods moved to top of their respective payment-method files.

Internationalization: Moved language strings

---

js/payment-methods/bitcoin.js
js/payment-methods/litecoin.js

See #16 
Notes:
* Refactored litecoin and bitcoin payment method code - to remove duplicate code. Litecoin payment method now inherits most of its functionality from the bitcoin payment method.

Issue 16: Better master public key checking

---

.gitignore
config.xml
index.html
package.json

- <access origin> added to allow https in android app
- script in package.json to run the app in a device without adding platform in order to use the fix version from config.xml, when we add platform it sets the last version and override the one in config.xml
- added meta for Content-Security-Policy
- icon added

changes to make app work in android

---

js/config.js
js/payment-methods/bitcoin.js
js/payment-methods/litecoin.js
js/services/blockexplorer.js
js/services/chain.so.js
js/util.js
js/views/settings-payment-method.js
js/views/settings.js
package.json

when setting xpub key in settings the app gets the first empty address in a gap limit and shows it for each currency in settings.

getting gap limit in settings

---

css/views/sample-addresses.css
html/templates/sample-addresses.html
js/config.js
js/lang/en.js
js/views/sample-addresses.js
js/views/settings.js

Show sample addresses from xpub (in settings)

---

js/services/coinbase.js
js/services/memory-cache.js

Helps performance of QR code rendering by caching exchange rate data

Added memory-cache service

---

css/header.css
css/views/admin.css
css/views/pay.css
html/templates/admin.html
js/lang/en.js
js/lang/fr.js
js/router.js
js/views/admin.js

Remove lock button when in admin area and lock the app when going out of the admin area.

Remove lock button when in admin area

---

js/device.js
js/views/about.js
js/views/payment-details.js

fix onback button payment details and about 

---

html/templates/amount.html
html/templates/number-pad.html
js/config.js
js/handlebars.extend/numbers.js
js/lang/en.js
js/payment-methods/bitcoin.js
js/payment-methods/monero.js
js/util.js
js/views/display-payment-address.js
js/views/number-pad.js
js/views/pay.js

number format setting #82

---

css/views/payment-timed-out.css
html/templates/payment-timed-out.html
js/config.js
js/lang/en.js
js/router.js
js/views/display-payment-address.js
js/views/payment-timed-out.js

save transaction as "timed-out" as per #130

payment-request-timed-out

---

css/slider.css
html/templates/slider.html
js/config.js
js/views/main.js
js/views/slider.js

* Issue #161: Slider in admin area
* Issue #160: Input field focus
* Issue #134: Admin area scroll

Touch fixes

---

css/views/display-payment-address.css
html/templates/pay-address.html
js/abstracts/payment-method.js
js/models/payment-request.js
js/payment-methods/bitcoin.js
js/router.js
js/views/choose-payment-method.js
js/views/display-payment-address.js
js/views/pay.js

Clean-up in payment screens to reduce number of payment requests
Clarified payment request model attributes

Payment requests "canceled" status

---

config.js
index.html
js/app.js
js/config.js
js/lang/en.js
js/services/ct-api.js
js/views/display-payment-address.js
tasks/compileHtml.js

Get exchange rates via sockets

Websockets with ct-api-server

---

js/device.js
js/payment-methods/bitcoin.js

Don't show text in camera view
Hide additional, unnecessary controls in camera view

Remove beep from camera usage

---

js/abstracts/payment-method.js
js/views/getting-started-payment-method-verify.js
js/views/getting-started.js

Hide payment-method-verified step if payment method has no verification
step

Disable next until verified view rendered

---

js/payment-methods/bitcoin-lightning.js

Added Bitcoin Lightning French translations.

Bitcoin Lightning French translations

---

CONTRIBUTING.md

Proposal for Contribution guide.

Added contribution guideline

---

css/header.css
js/abstracts/base-view.js
js/device.js
js/init.js
js/models/cache.js
js/models/payment-request.js
js/models/setting.js
js/payment-methods/bitcoin-lightning.js
js/router.js
js/views/admin.js
js/views/display-payment-address.js
js/views/main.js
js/views/slider.js

Should navigate back to General Settings screen when using back button
Refactored no-close current view code in Main view (still only Admin)

Fix back button regression in payment history

---

js/sound.js

Fix: sound works when cordova browser

---

js/config.js
js/lang/en.js
js/screen-saver.js

Feature: settings for screen saver

---

css/base.css
js/app.js
js/screen-saver.js

* Center busy UI vertically
* Pause and hide screen saver when app is busy

Busy UI fixes

---

css/secondary-controls.css
html/templates/getting-started-choose-payment-methods.html
html/templates/getting-started-done.html
html/templates/getting-started-general-settings.html
html/templates/getting-started-payment-method-settings.html
html/templates/getting-started-payment-method-verify.html
html/templates/getting-started-welcome.html
html/templates/payment-status.html
js/lang/cs.js
js/lang/de.js
js/lang/en.js
js/lang/es.js
js/views/getting-started.js

Change the styling in the getting started pages as well as in the payment-status view, to the current style of the buttons in the app.

Chore(secondary-buttons): changing style in remaining buttons
